### PR TITLE
Update to v1.9.x

### PR DESCRIPTION
**Pull request by franco-roura**
Hello! I really like your mod, so I updated the Forge API calls to make the mod compatible with v1.9.x.

I also made a few changes around the codebase, I hope you like it!

- Added new deferred registries for PointOfInterest objects, Menu types, and VillagerProfessions.
- Added locale translation to Argentinian Spanish.
- Added automatic code formatting for VSCode, the same XML file can also work with Eclipse or IntelliJ.
- Removed most unused imports.
- Added a generic try/catch wrapper around MenuScreen registering; in the new version of the Forge API the initialization of screens fails silently without any logs whenever there's something wrong.

### CODE REVIEW

**Comment by talhanation** [comment]
Hi, thank you for your PR, the mod had a bunch of bugs that need to be fixed first, but its cool that you made it work for 1.19.x


I will merge it. thx

**Comment by franco-roura** [comment]
Awesome! I did notice some weird behavior around the farmer and Workers not going home, so let me know which bug you think has most priority and your preferred gitflow, I’d like to help with those

**Comment by talhanation** [comment]
Ive verified your commits now. Do you have discord? I can add you there so you can have a look into the bugs in workers..

**Comment by talhanation** [comment]
https://discord.gg/f54QsX7r6a

**Comment by franco-roura** [comment]
Joined!

**Comment by FireRain4** [comment]
Please Tell me how to download jar on 1.19.2?

**Comment by franco-roura** [comment]
> Please Tell me how to download jar on 1.19.2?

It’s under heavy development but you can clone the repo and build the jar with gradle

**Comment by FireRain4** [comment]
Can you help with the Gradle? This is the first time I hear about such a program. I will be very grateful

**Comment by franco-roura** [comment]
> Can you help with the Gradle? This is the first time I hear about such a program. I will be very grateful

Sure, here's a link https://docs.gradle.org/current/userguide/more_about_tasks.html

**Comment by FireRain4** [comment]
Looks hard

**Pull request merged**
